send_message:
  name: Send message
  description: Send a text message to VK by peer_id.
  fields:
    message:
      required: true
      example: "Hello from Home Assistant"
      selector:
        text:
    title:
      required: false
      example: "Alert"
      selector:
        text:
    config_entry_id:
      required: false
      selector:
        text:
    recipient_id:
      required: false
      example: 2000000001
      selector:
        number:
    buttons:
      required: false
      example: |
        - - text: "Кнопка 1"
            command: mute1
          - text: "Кнопка 2"
            command: mute2
        - - text: "Кнопка 3"
            command: mute3
          - text: "Кнопка 4"
            command: mute4
      selector:
        text:
send_photo:
  name: Send photo
  description: Send a photo to VK by peer_id.
  fields:
    file:
      required: true
      example: "/config/www/photo.jpg"
      selector:
        text:
    caption:
      required: false
      example: "Camera snapshot"
      selector:
        text:
    config_entry_id:
      required: false
      selector:
        text:
    recipient_id:
      required: false
      example: 2000000001
      selector:
        number:
    buttons:
      required: false
      example: |
        - - text: "Mute"
            command: mute
            color: negative
      selector:
        text:
send_video:
  name: Send video
  description: Send a video to VK by peer_id.
  fields:
    file:
      required: true
      example: "/config/www/video.mp4"
      selector:
        text:
    caption:
      required: false
      example: "Camera clip"
      selector:
        text:
    video_access_token:
      required: true
      example: "vk1.a...."
      selector:
        text:
    config_entry_id:
      required: false
      selector:
        text:
    recipient_id:
      required: false
      example: 2000000001
      selector:
        number:
send_document:
  name: Send document
  description: Send a document/video file to VK by peer_id (docs attachment).
  fields:
    file:
      required: true
      example: "/config/www/video.mp4"
      selector:
        text:
    caption:
      required: false
      example: "Camera clip"
      selector:
        text:
    config_entry_id:
      required: false
      selector:
        text:
    recipient_id:
      required: false
      example: 2000000001
      selector:
        number:
    buttons:
      required: false
      example: |
        - - text: "Mute"
            command: mute
            color: negative
      selector:
        text:
